import AnimatedText from '@/components/AnimatedText'
import { LinkArrow } from '@/components/Icons'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import profilePic from '../../public/images/profile/PortfolioWebPagePic.png'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'


export default function Home() {
  return (
    <>
      <Head>
        <title>Aditya Anil Nair</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-2/5">
              <Image src={profilePic} alt="Aditya Anil Nair" className="w-full h-auto" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <h1>
                
              </h1>
              <AnimatedText text="Crafting Code That Brings Ideas To Life." className="!text-6xl !text-left"/>
              <p className="my-4 text-xl font-medium">
                Welcome to my portfolio. I specialize in full-stack web development and machine learning, 
                delivering tailored solutions that meet unique requirements. 
                My focus is on quality, efficiency, and innovation to transform your vision into reality. 
                Explore my latest projects, showcasing my expertise in React.js and web development.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link href="/Aditya Anil Nair - Resume.pdf" target={"_blank"}
                className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg 
                text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                download={true}
                >Resume <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link href="mailto:adityanil10@gmail.com" target={"_blank"}
                className="ml-4 text-lg font-medium capitalize text-dark underline">Contact Me</Link>
              </div>
            </div>
          </div>
        </Layout>
        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image src={lightBulb} alt="LightBulbImage" className="w-full h-auto" />
        </div>
      </main>
    </>
  )
}
